version: 1
pythonVersion: 3.8  # Change to the appropriate Python version if needed
prebuildCommand: python -c "from app import app, db; from flask.cli import FlaskGroup; FlaskGroup(app).create_all()"
buildCommand: pip install -r requirements.txt
startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT app:app
